### PR TITLE
Refactoring, reformat and fixes from @renemilk fork...

### PR DESCRIPTION
**Pull request by timofonic**
Autor:@renemilk

- refactor printing
- rewire find_group usage to allow nested groups
- pep8 reformat for manage_gitlab_project
- fix 'return value' printing of manage_gitlab

### CODE REVIEW

**Comment by samrocketman** [comment]
Before considering to merge this I would like @renemilk's permission to do so since they're the author.

**Comment by samrocketman** [comment]
This may need to be proposed/rewritten after #100 is merged.

**Comment by samrocketman** [comment]
Please do not pull request into `master` branch.  `master` is meant for stable and tested releases only.  Please open this pull request again on the `development` branch.  Refer to the [CONTRIBUTING.md](https://github.com/samrocketman/gitlab-mirrors/blob/master/CONTRIBUTING.md) document for details.

**Comment by renemilk** [comment]
I'm absolutely fine with merging any changes from my fork. I only did not set up a pull request myself since I considered the changes too localized and did not want to expend more effort to check for wider consequences of any changes.

**Pull request closed without merging**
